language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install:
  - gem install bundler
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails41.gemfile